import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "To-Do",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
